name: Bug Report
description: Think you found a bug? Let us know!
labels: [bug, to check]
body:
  - type: markdown
    attributes:
      value: |
        If you publish this issue, you accept that you made your own tests, and this is 100% a bug.
        You should have the steps to being able to reproduce this bug, for us to check if it's truly a bug.

        Also, you accept that, if this issue it's invalid in any way, will be discarded without receiving any response about it.
        If you're not sure if it's a bug, please [ask here](https://github.com/ezeholz/MMM-Remote-Control/discussions).
        
        Thanks for taking the time to help Remote Control get better every day!
  - type: input
    attributes:
      label: OS
      description: |
        example:
        - OS: Ubuntu 20.04
    validations:
      required: true
  - type: input
    attributes:
      label: NodeJS Version
      description: |
        example:
        - NodeJS: 14.17.5
      placeholder: '14.17.5'
    validations:
      required: true
  - type: input
    attributes:
      label: MagicMirror Version
      description: |
        example:
        - MM: 2.16.0
      placeholder: '2.16.0'
    validations:
      required: true
  - type: input
    attributes:
      label: Remote Control Version
      description: |
        example:
        - Remote Control: 2.3.6
      placeholder: '2.3.6'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Did you try using just Remote Control alone with MM?
      options:
      - label: I have and the error still happening
        required: true
  - type: textarea
    attributes:
      label: Description
      description: Short explanation of what you were going to do, what did you want to accomplish?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What should actually happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible solution
      description: You can suggest a reason for the bug, if know about it.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please give details about how do you reach that behavior
      placeholder: |
        1. Start MM...
        2. Wait until everything loads
        3. Click button...
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log
      description: |
        Paste the log you're getting, and possibly the error.
        **Please, make sure that none of your personal information, such as IP or passwords are exposed.**
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: config.js
      description: |
        Paste here your config.js file.

        Make sure that none of your personal data is present, specially check for:
        - IPs from MM instance, or the ones that are whitelisted. Please, replace them with *** so we're totally sure that you have set them.
        - API keys, Tokens from different modules, URL to private calendars.
        - Directions or Personal data.
      render: javascript
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional info
      description: Everything else that you think could be useful for us. ;D
    validations:
      required: false